services:
    noise_labs_website.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { leftmenu: @noise_labs_website.navbar_main_menu=, rightmenu: @noise_labs_website.navbar_right_menu= }
            - {}
            - { title: "noiselabs.org", titleRoute: "home", fixedTop: true, isFluid: false }
        tags:
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }

    noise_labs_website.navbar_menu_builder:
        class: NoiseLabs\Bundle\WebsiteBundle\Menu\NavbarMenuBuilder
        scope: request
        arguments: [ '@knp_menu.factory', '@security.context' ]

    noise_labs_website.navbar_main_menu:
        class: Knp\Menu\MenuItem
        factory_service: noise_labs_website.navbar_menu_builder
        factory_method: createMainMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    noise_labs_website.navbar_right_menu:
        class: Knp\Menu\MenuItem
        factory_service: noise_labs_website.navbar_menu_builder
        factory_method: createRightSideDropdownMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }